<%@ Page Language="VB" MasterPageFile="~/CenterAdmin/CenterAdminMasterPage.master" AutoEventWireup="false" CodeFile="WebsiteManagement.aspx.vb" Inherits="CenterAdmin_WebsiteManagement" title="Center Page Management" %>
<%@ Register Namespace = "RadixAjaxControls" TagPrefix="RadixControl" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="cc1" %>


<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">


   
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td>
                <table >
                    <tr>
                        <td width = "10px">
                        </td>
                        <td class="TextTitle">
                            Center Webpage Management
                        </td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr>
            <td style="margin-left: 40px">
                <asp:UpdatePanel ID="UpdatePanel9" runat="server">
                    <ContentTemplate>
                        <cc1:TabContainer ID="TabContainerWebpageManagement" runat="server" 
                            ActiveTabIndex="1" CssClass="ajax__myTab" Width="100%">
                            <cc1:TabPanel ID="TabSettings" runat="server"><HeaderTemplate>Settings</HeaderTemplate><ContentTemplate><br /><table style="width:100%;"><tr><td>Do you have your own website that you would like users to view instead of your Radix Systems center webpage? If so, tick the checkbox below and enter your website URL in the textbox. When you are ready click on the Submit button at the bottom of the page. <br /><br />Users will now be redirected to the website entered. To disable this feature and use the Radix Systems Center Webpage, uncheck the checkbox below and navigate through the other tabs.</td></tr><tr><td align="center"><br /><asp:CheckBox ID="chkRedirectUsers" runat="server" AutoPostBack="True" 
                                                    Text="I would like to re-direct users to my own website." /><br /></td></tr><tr><td><br /><table align="center" width="100%"><tr><td class="titlecell">My Website URL</td><td><asp:TextBox ID="txtCustomUrl" runat="server" Width="400px"></asp:TextBox></td></tr><tr><td class="titlecell">&#160;</td><td>&#160;</td></tr><tr><td class="titlecell">&#160;</td><td><asp:Button ID="btnCustomUrlSubmit" runat="server" CssClass="ButtonLightBlue" 
                                                                Text="Submit" /></td></tr></table><br /></td></tr></table><br /></ContentTemplate></cc1:TabPanel>
                            <cc1:TabPanel ID="TabHeader" runat="server"><HeaderTemplate>Header</HeaderTemplate><ContentTemplate><asp:UpdatePanel ID="UpdatePanel2" runat="server"><ContentTemplate><asp:Panel ID="pnlHeaderTop" runat="server" CssClass="TabsInnerExtension" 
                                                Height="25px" Width="100%"><table border="0" cellpadding="0" cellspacing="0"><tr><td width="15px"></td><td height="25px" valign="middle"><asp:LinkButton ID="lnkBanner" runat="server" CssClass="Link">Change Banner</asp:LinkButton>&#160;<asp:Label ID="Label3" runat="server" CssClass="GrayText" Text="|"></asp:Label>&#160;<asp:LinkButton ID="lnkLogo" runat="server" CssClass="Link">Center Logo</asp:LinkButton>&#160;<asp:Label ID="Label4" runat="server" CssClass="GrayText" Text="|"></asp:Label>&#160;<asp:LinkButton ID="lnkStyle" runat="server" CssClass="Link">Styles</asp:LinkButton></td></tr></table></asp:Panel><br /><table width="100%"><tr><td>Below is a <b>sample</b> of how your website is currently viewed. </td></tr><tr><td align="center" valign="middle"><br /><table style="border:dashed 1px #E4E4E4;" width="100%"><tr><td align="left" valign="middle">&#160;&#160;&#160;<asp:Image ID="imgCenterLogo" runat="server" />&#160;&#160;<asp:Label ID="lblCenterName" runat="server" Text="Center Name"></asp:Label></td></tr><tr><td><table width="100%"><tr><td style="height:20px;"><div><span style="position:absolute;"><asp:Image ID="imgBanner" runat="server" AlternateText="Preview Banner" 
                                                                                        Height="157px" Width="690px" /></span><span style="position:absolute; padding-top:100px; padding-left:50px; z-index:2; "><asp:Label ID="lblSlogan" runat="server" Font-Size="Large" Text="Label"></asp:Label></span></div></td></tr><tr><td style="height:170px;" valign="bottom"><marquee ID="MovingText2" runat="server" direction="left" scrollamount="2" 
                                                                                    scrolldelay="175"> <asp:Label ID="lblMarquee" runat="server" Text="Label"></asp:Label></marquee> </td></tr></table></td></tr></table><br /></td></tr><tr><td align="center" valign="middle"><asp:MultiView ID="mvHeader" runat="server"><br /><asp:View ID="vChangeBanner" runat="server"><table width="100%"><tr><td>To change, choose a banner from one of the options below or you may upload your own banner.</td></tr><tr><td><br /><table align="center" width="90%"><tr><td height="150px" width="40px"><asp:RadioButton ID="rdbA" runat="server" BorderStyle="None" GroupName="Banner" 
                                                                                            Text="A" /></td><td valign="middle"><asp:Image ID="imgA" runat="server" Height="118px" ImageAlign="Middle" 
                                                                                            ImageUrl="~/Centers/Images/Banners/Banner1.png" Width="519px" /></td></tr><tr><td height="150px" width="40px"><asp:RadioButton ID="rdbB" runat="server" BorderStyle="None" GroupName="Banner" 
                                                                                            Text="B" /></td><td valign="middle"><asp:Image ID="imgB" runat="server" Height="118px" ImageAlign="Middle" 
                                                                                            ImageUrl="~/Centers/Images/Banners/Banner2.png" Width="519px" /></td></tr><tr><td height="150px" width="40px"><asp:RadioButton ID="rdbC" runat="server" BorderStyle="None" GroupName="Banner" 
                                                                                            Text="C" /></td><td valign="middle"><asp:Image ID="imgB0" runat="server" Height="118px" ImageAlign="Middle" 
                                                                                            ImageUrl="~/Centers/Images/Banners/Banner3.png" Width="519px" /></td></tr><tr><td height="150px" width="40px"><asp:RadioButton ID="rdbD" runat="server" BorderStyle="None" GroupName="Banner" 
                                                                                            Text="D" /></td><td valign="middle"><asp:Image ID="imgB1" runat="server" Height="118px" ImageAlign="Middle" 
                                                                                            ImageUrl="~/Centers/Images/Banners/Banner4.png" Width="519px" /></td></tr><tr><td height="150px" width="40px"><asp:RadioButton ID="rdbE" runat="server" BorderStyle="None" GroupName="Banner" 
                                                                                            Text="E" /></td><td valign="middle"><asp:Image ID="imgB2" runat="server" Height="118px" ImageAlign="Middle" 
                                                                                            ImageUrl="~/Centers/Images/Banners/Banner5.png" Width="519px" /></td></tr><tr><td height="150px" width="40px"><asp:RadioButton ID="rdbF" runat="server" BorderStyle="None" GroupName="Banner" 
                                                                                            Text="F" /></td><td valign="middle"><asp:Image ID="imgB3" runat="server" Height="118px" ImageAlign="Middle" 
                                                                                            ImageUrl="~/Centers/Images/Banners/Banner6.png" Width="519px" /></td></tr><tr><td height="150px" width="40px"><asp:RadioButton ID="rdbG" runat="server" BorderStyle="None" GroupName="Banner" 
                                                                                            Text="G" /></td><td valign="top"><br /><table style="width:100%;"><tr><td>Upload my own banner:</td></tr><tr><td><br /><asp:FileUpload ID="FileUpload1" runat="server" CssClass="FileUploader" 
                                                                                                        Width="500px" /><br /><br /><br /><asp:Button ID="Button1" runat="server" CssClass="ButtonLightBlue" 
                                                                                                        Text="Upload" /></td></tr></table></td></tr></table><br /></td></tr><tr><td align="center" height="40px" valign="middle"><asp:Button ID="btnUpdateHeader" runat="server" CssClass="ButtonLightBlue" 
                                                                                Text="Update" /></td></tr></table></asp:View><br /><asp:View ID="vCenterLogo" runat="server"><table width="100%"><tr><td>To change you logo, choose a logo from one of the options below or you may upload your own logo at the bottom of the page.</td></tr><tr><td><br /><table align="center" width="90%"><tr><td align="center" height="150px" width="33%"><asp:Image ID="imgLogoA" runat="server" 
                                                                                            ImageUrl="~/Centers/Images/Logos/Logo1.png" /></td><td align="center" valign="middle" width="33%"><asp:Image ID="imgLogoB" runat="server" 
                                                                                            ImageUrl="~/Centers/Images/Logos/Logo2.png" /></td><td align="center" valign="middle"><asp:Image ID="imgLogoC" runat="server" 
                                                                                            ImageUrl="~/Centers/Images/Logos/Logo3.png" /></td></tr><tr align="center"><td align="center"><asp:RadioButton ID="rdbLogoA" runat="server" BorderStyle="None" 
                                                                                            GroupName="Logo" Text="A" /></td><td valign="middle"><asp:RadioButton ID="rdbLogoB" runat="server" BorderStyle="None" 
                                                                                            GroupName="Logo" Text="B" /></td><td valign="middle"><asp:RadioButton ID="rdbLogoC" runat="server" BorderStyle="None" 
                                                                                            GroupName="Logo" Text="C" /></td></tr></table><br /><br /><table align="center"><tr><td>&#160;</td><td align="left">Upload my own logo:</td></tr><tr><td align="center" width="50px"><asp:RadioButton ID="rdbLogoD" runat="server" BorderStyle="None" 
                                                                                            GroupName="Logo" Text="D" /></td><td align="left"><br /><asp:FileUpload ID="FileUpload2" runat="server" CssClass="FileUploader" 
                                                                                            Width="500px" /><br /><br /><br /><asp:Button ID="btnUploadLogo" runat="server" CssClass="ButtonLightBlue" 
                                                                                            Text="Upload" /></td></tr></table><br /><br /></td></tr><tr><td align="center" height="40px" valign="middle"><asp:Button ID="btnUpdateLogo" runat="server" CssClass="ButtonLightBlue" 
                                                                                Text="Update" /></td></tr></table></asp:View><br /><asp:View ID="vStyles" runat="server"><table style="width:100%;"><tr><td align="left">You may setup the visual appearence and styles of your header typography here.</td></tr><tr><td><asp:UpdatePanel ID="UpdatePanel3" runat="server"><ContentTemplate><br /><table align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Center Name</td></tr><tr><td align="right" class="titlecell" valign="top">Preview:</td><td align="left" height="60" valign="top"><asp:Label ID="lblCenterNamePreview" runat="server" Text="Label"></asp:Label></td></tr><tr><td align="right" class="titlecell">Forecolor:</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtForecolorCenter" runat="server" AutoPostBack="True" 
                                                                                                                CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtForecolorCenter_ColorPickerExtender" 
                                                                                                                runat="server" Enabled="True" PopupButtonID="imgbtnColorPickerCenter" 
                                                                                                                SampleControlID="pnlColorPreviewCenter" TargetControlID="txtForecolorCenter"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerCenter" runat="server" 
                                                                                                                ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewCenter" runat="server" BorderColor="#CCCCCC" 
                                                                                                                BorderStyle="Solid" BorderWidth="1px" Height="15px" HorizontalAlign="Center" 
                                                                                                                Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorCenter" runat="server" 
                                                                                                                CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Styles:</td><td align="left"><table border="0" cellpadding="0" cellspacing="0" style="width: 80%;"><tr><td><asp:CheckBox ID="chkBold" runat="server" AutoPostBack="True" Font-Bold="True" 
                                                                                                                Text="Bold" /></td><td><asp:CheckBox ID="chkItalic" runat="server" AutoPostBack="True" 
                                                                                                                Font-Italic="True" Text="Italic" /></td><td><asp:CheckBox ID="chkUnderline" runat="server" AutoPostBack="True" 
                                                                                                                Font-Underline="True" Text="Underline" /></td><td><asp:CheckBox ID="chkStrikeout" runat="server" AutoPostBack="True" 
                                                                                                                Font-Strikeout="True" Text="Strikeout" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Font Size:</td><td align="left" valign="middle">&#160;<asp:Label ID="lblFontSizeCenter" runat="server" Text="Label"></asp:Label>&#160;&#160;<asp:ImageButton ID="imgbtnUp" runat="server" 
                                                                                                    ImageUrl="~/Images/Icons/Up.png" style="height: 11px" /><asp:ImageButton ID="imgbtnDown" runat="server" 
                                                                                                    ImageUrl="~/Images/Icons/Down.png" /></td></tr><tr><td align="right" class="titlecell">Font Family:</td><td align="left"><asp:DropDownList ID="ddlFontsCenterName" runat="server" AutoPostBack="True"></asp:DropDownList></td></tr></table><br /></ContentTemplate></asp:UpdatePanel><br /></td></tr><tr><td><asp:UpdatePanel ID="UpdatePanel4" runat="server"><ContentTemplate><table ID="tblCenterName0" align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Center Slogan</td></tr><tr><td align="right" class="titlecell" valign="middle">Preview:</td><td align="left" valign="middle"><asp:Label ID="lblCenterSloganPreview" runat="server" Text="Label"></asp:Label></td></tr><tr><td align="right" class="titlecell">Slogan:</td><td align="left"><asp:TextBox ID="txtSlogan" runat="server" CssClass="TextBox" Width="400px"></asp:TextBox></td></tr><tr><td align="right" class="titlecell">Forecolor:</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtForecolorSlogan" runat="server" AutoPostBack="True" 
                                                                                                                CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtForecolorSlogan_ColorPickerExtender" 
                                                                                                                runat="server" Enabled="True" PopupButtonID="imgbtnColorPickerSlogan" 
                                                                                                                SampleControlID="pnlColorPreviewSlogan" TargetControlID="txtForecolorSlogan"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerSlogan" runat="server" 
                                                                                                                ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewSlogan" runat="server" BorderColor="#CCCCCC" 
                                                                                                                BorderStyle="Solid" BorderWidth="1px" Height="15px" HorizontalAlign="Center" 
                                                                                                                Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorSlogan" runat="server" 
                                                                                                                CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Styles:</td><td align="left"><table border="0" cellpadding="0" cellspacing="0" style="width: 80%;"><tr><td><asp:CheckBox ID="chkBold0" runat="server" AutoPostBack="True" Font-Bold="True" 
                                                                                                                Text="Bold" /></td><td><asp:CheckBox ID="chkItalic0" runat="server" AutoPostBack="True" 
                                                                                                                Font-Italic="True" Text="Italic" /></td><td><asp:CheckBox ID="chkUnderline0" runat="server" AutoPostBack="True" 
                                                                                                                Font-Underline="True" Text="Underline" /></td><td><asp:CheckBox ID="chkStrikeout0" runat="server" AutoPostBack="True" 
                                                                                                                Font-Strikeout="True" Text="Strikeout" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Font Size:</td><td align="left" valign="middle">&#160;<asp:Label ID="lblFontSizeSlogan" runat="server" Text="Label"></asp:Label>&#160;&#160;<asp:ImageButton ID="imgbtnUp0" runat="server" 
                                                                                                    ImageUrl="~/Images/Icons/Up.png" /><asp:ImageButton ID="imgbtnDown0" runat="server" 
                                                                                                    ImageUrl="~/Images/Icons/Down.png" /></td></tr><tr><td align="right" class="titlecell">Font Family:</td><td align="left"><asp:DropDownList ID="ddlFontsCenterSlogan" runat="server" AutoPostBack="True"></asp:DropDownList></td></tr></table><br /></ContentTemplate></asp:UpdatePanel><br /></td></tr><tr><td align="left"><asp:UpdatePanel ID="UpdatePanel5" runat="server"><ContentTemplate><table ID="tblCenterName1" align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Moving Healines</td></tr><tr><td align="right" class="titlecell" valign="middle">Preview:</td><td align="left" valign="middle"><asp:Label ID="lblCenterHeadlines" runat="server" Text="Label"></asp:Label></td></tr><tr><td align="right" class="titlecell" valign="top">Headlines:</td><td align="left"><RadixControl:cHTMLEditor ID="Headline" runat="server" Height="150px" 
                                                                                                    Width="100%" /><br /><asp:Button ID="btnPreviewHtmlHeadline" runat="server" 
                                                                                                    CssClass="ButtonLightBlue" Text="Update Preview" /></td></tr><tr><td align="right" class="titlecell">Font Size:</td><td align="left" valign="middle">&#160;<asp:Label ID="lblFontSizeHeadline" runat="server" Text="Label"></asp:Label>&#160;&#160;<asp:ImageButton ID="imgbtnUp1" runat="server" 
                                                                                                    ImageUrl="~/Images/Icons/Up.png" /><asp:ImageButton ID="imgbtnDown1" runat="server" 
                                                                                                    ImageUrl="~/Images/Icons/Down.png" /></td></tr><tr><td align="right" class="titlecell">Font Family:</td><td align="left"><asp:DropDownList ID="ddlFontsCenterHeadline" runat="server" 
                                                                                                    AutoPostBack="True"></asp:DropDownList></td></tr></table><br /></ContentTemplate></asp:UpdatePanel><br /></td></tr><tr><td><br /></td></tr><tr><td><asp:Button ID="btnApplyChanges" runat="server" CssClass="ButtonLightBlue" 
                                                                                Text="Apply Changes" /></td></tr></table></asp:View><br /><br /></asp:MultiView></td></tr><tr><td align="center" valign="middle">&#160;</td></tr></table><br /><asp:Panel ID="pnlSettingsBottom" runat="server" CssClass="TabsInnerExtension" 
                                                Height="25px" Width="100%"><table border="0" cellpadding="0" cellspacing="0"><tr><td width="15px"></td><td height="25px" valign="middle"><asp:LinkButton ID="lnkBanner2" runat="server" CssClass="Link">Change Banner</asp:LinkButton>&#160;<asp:Label ID="Label9" runat="server" CssClass="GrayText" Text="|"></asp:Label>&#160;<asp:LinkButton ID="lnkLogo2" runat="server" CssClass="Link">Center Logo</asp:LinkButton>&#160;<asp:Label ID="Label10" runat="server" CssClass="GrayText" Text="|"></asp:Label>&#160;<asp:LinkButton ID="lnkStyle2" runat="server" CssClass="Link">Styles</asp:LinkButton></td></tr></table></asp:Panel></ContentTemplate></asp:UpdatePanel></ContentTemplate></cc1:TabPanel>
                            <cc1:TabPanel ID="TabContent" runat="server"><HeaderTemplate>Content</HeaderTemplate><ContentTemplate><asp:UpdatePanel ID="UpdatePanel1" runat="server"><ContentTemplate><asp:Panel ID="Panel2" runat="server" CssClass="TabsInnerExtension" 
                                                Height="25px" Width="100%"><table border="0" cellpadding="0" cellspacing="0"><tr><td width="15px"></td><td height="25px" valign="middle"><asp:LinkButton ID="lnkTopLeft" runat="server" CssClass="Link">Top Left Panel</asp:LinkButton>&#160;<asp:Label ID="Label5" runat="server" CssClass="GrayText" Text="|"></asp:Label>&#160;<asp:LinkButton ID="lnkBottomLeft" runat="server" CssClass="Link">Bottom Left Panel</asp:LinkButton>&nbsp;<asp:Label ID="Label6" runat="server" CssClass="GrayText" Text="|"></asp:Label>&#160;<asp:LinkButton ID="lnkTopRight" runat="server" CssClass="Link">Top Right Panel</asp:LinkButton></td></tr></table></asp:Panel><br /><asp:MultiView ID="mvContent" runat="server"><asp:View ID="vTopLeft" runat="server"><table align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Top Left Content Panel</td></tr><tr><td class="titlecell">Content Title</td><td><asp:TextBox ID="txtTopLeftTitle" runat="server" CssClass="TextBox" 
                                                                    Width="350px"></asp:TextBox></td></tr><tr><td class="titlecell" valign="top">Content</td><td><RadixControl:cHTMLEditor ID="HtmlTopLeftContent" runat="server" Height="400px" 
                                                                    Width="100%" /></td></tr><tr><td class="titlecell">&#160;</td><td><asp:Button ID="btnUpdateTopLeft" runat="server" CssClass="ButtonLightBlue" 
                                                                    Text="Update Content" /></td></tr></table><br /><br /></asp:View><asp:View ID="vBottomLeft" runat="server"><table align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Bottom Left Content Panel</td></tr><tr><td class="titlecell">Content Title</td><td><asp:TextBox ID="txtBottomLeftTitle" runat="server" CssClass="TextBox" 
                                                                    Width="350px"></asp:TextBox></td></tr><tr><td class="titlecell" valign="top">Content</td><td><RadixControl:cHTMLEditor ID="HtmlBottomLeftContent" runat="server" 
                                                                    Height="400px" Width="100%" /></td></tr><tr><td class="titlecell">&#160;</td><td><asp:Button ID="btnUpdateBottomLeft" runat="server" CssClass="ButtonLightBlue" 
                                                                    Text="Update Content" /></td></tr></table></asp:View><asp:View ID="vTopRight" runat="server"><table align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Top Right Content Panel</td></tr><tr><td class="titlecell">&#160;</td><td>Would you like to display your contact details in this panel? <p /><asp:CheckBox ID="chkContactDetails" runat="server" AutoPostBack="True" 
                                                                        Text="Show Contact Details" /></td></tr><tr><td class="titlecell">Content Title</td><td><asp:TextBox ID="txtTopRightTitle" runat="server" CssClass="TextBox" 
                                                                        Width="350px"></asp:TextBox></td></tr><tr><td class="titlecell" valign="top">Content</td><td><RadixControl:cHTMLEditor ID="HtmlTopRightContent" runat="server" 
                                                                        Height="400px" Width="100%" /></td></tr><tr><td class="titlecell">&#160;</td><td><asp:Button ID="btnUpdateTopRight" runat="server" CssClass="ButtonLightBlue" 
                                                                        Text="Update Content" /></td></tr></table></asp:View></asp:MultiView><br /></ContentTemplate></asp:UpdatePanel></ContentTemplate></cc1:TabPanel>
                                <cc1:TabPanel ID="TabAppearance" runat="server"><HeaderTemplate>General Appearance</HeaderTemplate><ContentTemplate><asp:UpdatePanel ID="UpdatePanel7" runat="server"><ContentTemplate><asp:Panel ID="Panel3" runat="server" CssClass="TabsInnerExtension" 
                                                    Height="25px" Width="100%"><table border="0" cellpadding="0" cellspacing="0"><tr><td width="15px"></td><td height="25px" valign="middle"><asp:LinkButton ID="lnkContentStyles" runat="server" CssClass="Link">Content Styles</asp:LinkButton>&#160;<asp:Label ID="Label7" runat="server" CssClass="GrayText" Text="|"></asp:Label>&#160;<asp:LinkButton ID="lnkPageColours" runat="server" CssClass="Link">Page Styles</asp:LinkButton>&#160;</td></tr></table></asp:Panel><asp:MultiView ID="mvAppearance" runat="server"><asp:View ID="vContentStyles" runat="server"><asp:UpdatePanel ID="UpdatePanel6" runat="server"><ContentTemplate><table align="center" width="90%"><tr><td style="height:100px" valign="top"><table width="98%"><tr><td align="center"><asp:Panel ID="SampleContentTitlePanel" runat="server"><table width="100%"><tr><td align="center" width="20"><asp:Image ID="imgCollapse" runat="server" ImageUrl="~/Images/collapse.png" /></td><td align="left"><asp:Label ID="lblSampleTitle" runat="server" Text="This Is A Sample Title"></asp:Label></td></tr></table></asp:Panel><cc1:RoundedCornersExtender ID="SampleContentTitlePanel_RoundedCornersExtender" 
                                                                                            runat="server" Enabled="True" TargetControlID="SampleContentTitlePanel"></cc1:RoundedCornersExtender></td></tr></table><cc1:CollapsiblePanelExtender ID="SampleContentPanel_CollapsiblePanelExtender" 
                                                                                runat="server" CollapseControlID="SampleContentTitlePanel" 
                                                                                CollapsedImage="~/Images/collapse.png" Enabled="True" 
                                                                                ExpandControlID="SampleContentTitlePanel" ExpandedImage="~/Images/expand.png" 
                                                                                ImageControlID="imgCollapse" SuppressPostBack="True" 
                                                                                TargetControlID="SampleContentPanel"></cc1:CollapsiblePanelExtender><asp:Panel ID="SampleContentPanel" runat="server"><div style="text-align:justify  "><table width="98%"><tr><td align="justify"><asp:Label ID="lblSampleContent" runat="server" 
                                                                                                    Text="Maecenas porttitor, odio quis interdum pretium, eros urna volutpat lorem, at tincidunt diam mi vitae nisl. Mauris ornare blandit adipiscing. Duis vel odio nunc. Nulla malesuada accumsan orci, ultrices dictum erat porttitor sit amet. Maecenas sed odio quis lacus faucibus euismod. Nullam nisi eros, dictum et laoreet a, convallis et mi. Cras porta placerat ligula et cursus."></asp:Label><br /></td></tr></table></div></asp:Panel></td></tr></table><br /><br /><table align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Content Title Style</td></tr><tr><td align="right" class="titlecell">Forecolor</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtForecolorContentTitle" runat="server" AutoPostBack="True" 
                                                                                            CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtForecolorContentTitle_ColorPickerExtender" 
                                                                                            runat="server" Enabled="True" PopupButtonID="imgbtnColorPickerContentTitle" 
                                                                                            SampleControlID="pnlColorPreviewContentTitle" 
                                                                                            TargetControlID="txtForecolorContentTitle"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerContentTitle" runat="server" 
                                                                                            ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewContentTitle" runat="server" 
                                                                                            BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="15px" 
                                                                                            HorizontalAlign="Center" Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorCenter0" runat="server" 
                                                                                            CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Styles</td><td align="left"><table border="0" cellpadding="0" cellspacing="0" style="width: 80%;"><tr><td><asp:CheckBox ID="chkBoldContentTitle" runat="server" AutoPostBack="True" 
                                                                                            Font-Bold="True" Text="Bold" /></td><td><asp:CheckBox ID="chkItalicContentTitle" runat="server" AutoPostBack="True" 
                                                                                            Font-Italic="True" Text="Italic" /></td><td><asp:CheckBox ID="chkUnderlineContentTitle" runat="server" AutoPostBack="True" 
                                                                                            Font-Underline="True" Text="Underline" /></td><td><asp:CheckBox ID="chkStrikeoutContentTitle" runat="server" AutoPostBack="True" 
                                                                                            Font-Strikeout="True" Text="Strikeout" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Font Size</td><td align="left" valign="middle">&#160;<asp:Label ID="lblFontSizeContentTitle" runat="server" Text="Label"></asp:Label>&#160;&#160;<asp:ImageButton ID="imgbtnUp2" runat="server" 
                                                                                ImageUrl="~/Images/Icons/Up.png" /><asp:ImageButton ID="imgbtnDown2" runat="server" 
                                                                                ImageUrl="~/Images/Icons/Down.png" /></td></tr><tr><td align="right" class="titlecell">Font Family</td><td align="left"><asp:DropDownList ID="ddlFontsContentTitle" runat="server" AutoPostBack="True"></asp:DropDownList></td></tr><tr><td align="right" class="titlecell">&#160;</td><td align="left">&#160;</td></tr><tr><td align="right" class="titlecell">Background Color</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtBackgroundContentTitle" runat="server" AutoPostBack="True" 
                                                                                            CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtBackgroundContentTitle_ColorPickerExtender" 
                                                                                            runat="server" Enabled="True" 
                                                                                            PopupButtonID="imgbtnColorPickerContentTitleBackground" 
                                                                                            SampleControlID="pnlColorPreviewContentTitleBackground" 
                                                                                            TargetControlID="txtBackgroundContentTitle"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerContentTitleBackground" runat="server" 
                                                                                            ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewContentTitleBackground" runat="server" 
                                                                                            BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="15px" 
                                                                                            HorizontalAlign="Center" Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorCenter3" runat="server" 
                                                                                            CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Corner Radius</td><td align="left">&#160;<asp:Label ID="lblCornerRadiusContentPanel" runat="server" Text="Label"></asp:Label>&#160;&#160;<asp:ImageButton ID="imgbtnUp5" runat="server" 
                                                                                ImageUrl="~/Images/Icons/Up.png" style="height: 11px" /><asp:ImageButton ID="imgbtnDown5" runat="server" 
                                                                                ImageUrl="~/Images/Icons/Down.png" /></td></tr><tr><td align="right" class="titlecell">Border Color</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtBorderContentTitle" runat="server" AutoPostBack="True" 
                                                                                            CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtBorderContentTitle_ColorPickerExtender" 
                                                                                            runat="server" Enabled="True" 
                                                                                            PopupButtonID="imgbtnColorPickerContentTitleBorder" 
                                                                                            SampleControlID="pnlColorPreviewContentTitleBorder" 
                                                                                            TargetControlID="txtBorderContentTitle"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerContentTitleBorder" runat="server" 
                                                                                            ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewContentTitleBorder" runat="server" 
                                                                                            BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="15px" 
                                                                                            HorizontalAlign="Center" Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorCenter2" runat="server" 
                                                                                            CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Corner Style</td><td align="left"><asp:DropDownList ID="ddlCornerStyleContentTitle" runat="server"></asp:DropDownList></td></tr></table><br /><table ID="tblCenterName4" align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Content Panel Style</td></tr><tr><td align="right" class="titlecell">Font Size:</td><td align="left" valign="middle">&#160;<asp:Label ID="lblFontSizeContentPanel" runat="server" Text="Label"></asp:Label>&#160;&#160;<asp:ImageButton ID="imgbtnUp4" runat="server" 
                                                                                ImageUrl="~/Images/Icons/Up.png" /><asp:ImageButton ID="imgbtnDown4" runat="server" 
                                                                                ImageUrl="~/Images/Icons/Down.png" /></td></tr><tr><td align="right" class="titlecell">Font Family:</td><td align="left"><asp:DropDownList ID="ddlFontsContentPanel" runat="server" AutoPostBack="True"></asp:DropDownList></td></tr><tr><td align="right" class="titlecell">&#160;</td><td align="left">&#160;</td></tr><tr><td align="right" class="titlecell">&#160;</td><td align="left"><asp:Button ID="btnUpdateContentStyles" runat="server" 
                                                                                CssClass="ButtonLightBlue" Text="Update Content Styles" Width="130px" /></td></tr></table><br /><br /></ContentTemplate></asp:UpdatePanel></asp:View><asp:View ID="vPageStyles" runat="server"><asp:UpdatePanel ID="UpdatePanel8" runat="server"><ContentTemplate><br /><asp:Table ID="tblSamplePage" runat="server" HorizontalAlign="Center" 
                                                                    width="90%"><asp:TableRow><asp:TableCell HorizontalAlign="Center"><br /><i>Sample Page Preview<br /></i><br /><asp:Panel ID="pnlPreviewPanel" runat="server" Width="85%"><br /><br /><i>Sample Main Panel</i><br /><br /><br /></asp:Panel><cc1:RoundedCornersExtender ID="pnlPreviewPanel_RoundedCornersExtender" 
                                                                            runat="server" Enabled="True" TargetControlID="pnlPreviewPanel"></cc1:RoundedCornersExtender><br /><br /></asp:TableCell></asp:TableRow></asp:Table><br /><br /><table align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Main Panel Styles</td></tr><tr><td align="right" class="titlecell">&#160;</td><td align="left">&#160;</td></tr><tr><td align="right" class="titlecell">Background Color</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtBackgroundMainPanel" runat="server" AutoPostBack="True" 
                                                                                            CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtBackgroundMainPanel_ColorPickerExtender" 
                                                                                            runat="server" Enabled="True" 
                                                                                            PopupButtonID="imgbtnColorPickerBackgroundMainPanel" 
                                                                                            SampleControlID="pnlColorPreviewBackgroundMainPanel" 
                                                                                            TargetControlID="txtBackgroundMainPanel"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerBackgroundMainPanel" runat="server" 
                                                                                            ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewBackgroundMainPanel" runat="server" 
                                                                                            BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="15px" 
                                                                                            HorizontalAlign="Center" Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorCenter5" runat="server" 
                                                                                            CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Corner Radius</td><td align="left">&#160;<asp:Label ID="lblCornerRadiusMainPanel" runat="server" Text="Label"></asp:Label>&#160;&#160;<asp:ImageButton ID="imgbtnUp7" runat="server" 
                                                                                ImageUrl="~/Images/Icons/Up.png" style="height: 11px" /><asp:ImageButton ID="imgbtnDown7" runat="server" 
                                                                                ImageUrl="~/Images/Icons/Down.png" /></td></tr><tr><td align="right" class="titlecell">Border Color</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtBorderMainPanel" runat="server" AutoPostBack="True" 
                                                                                            CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtBorderMainPanel_ColorPickerExtender" 
                                                                                            runat="server" Enabled="True" PopupButtonID="imgbtnColorPickerBorderMainPanel" 
                                                                                            SampleControlID="pnlColorPreviewBorderMainPanel" 
                                                                                            TargetControlID="txtBorderMainPanel"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerBorderMainPanel" runat="server" 
                                                                                            ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewBorderMainPanel" runat="server" 
                                                                                            BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="15px" 
                                                                                            HorizontalAlign="Center" Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorCenter6" runat="server" 
                                                                                            CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">Corner Style</td><td align="left"><asp:DropDownList ID="ddlCornerStyleMainPanel" runat="server"></asp:DropDownList></td></tr><tr><td align="right" class="titlecell">Panel Stripes</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtPanelStripesMainPanel" runat="server" AutoPostBack="True" 
                                                                                            CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtPanelStripesMainPanel_ColorPickerExtender" 
                                                                                            runat="server" Enabled="True" PopupButtonID="imgbtnColorPickerStripesMainPanel" 
                                                                                            SampleControlID="pnlColorPreviewStripesMainPanel" 
                                                                                            TargetControlID="txtPanelStripesMainPanel"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerStripesMainPanel" runat="server" 
                                                                                            ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewStripesMainPanel" runat="server" 
                                                                                            BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="15px" 
                                                                                            HorizontalAlign="Center" Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorCenter7" runat="server" 
                                                                                            CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr><tr><td align="right" class="titlecell">&#160;</td><td align="left">&#160;</td></tr></table><br /><br /><table ID="tblCenterName3" align="center" width="90%"><tr><td align="left" class="BlueTextLightBold" colspan="2">Page Styles</td></tr><tr><td align="right" class="titlecell">Background</td><td align="left"><table border="0" cellpadding="0" cellspacing="0"><tr valign="middle"><td><asp:TextBox ID="txtBackgroundPage" runat="server" AutoPostBack="True" 
                                                                                            CssClass="TextBox" MaxLength="6" Width="100px"></asp:TextBox><cc1:ColorPickerExtender ID="txtBackgroundPage_ColorPickerExtender" 
                                                                                            runat="server" Enabled="True" PopupButtonID="imgbtnColorPickerBackgroundPage" 
                                                                                            SampleControlID="pnlColorPreviewBackgroundPage" 
                                                                                            TargetControlID="txtBackgroundPage"></cc1:ColorPickerExtender></td><td>&#160;&#160;<asp:ImageButton ID="imgbtnColorPickerBackgroundPage" runat="server" 
                                                                                            ImageUrl="~/Images/Icons/paint.png" />&#160;&#160;</td><td align="center" valign="middle" width="30"><asp:Panel ID="pnlColorPreviewBackgroundPage" runat="server" 
                                                                                            BorderColor="#CCCCCC" BorderStyle="Solid" BorderWidth="1px" Height="15px" 
                                                                                            HorizontalAlign="Center" Width="15px"></asp:Panel></td><td><asp:Button ID="btnApplyForecolorCenter1" runat="server" 
                                                                                            CssClass="ButtonLightBlue" Text="Apply" /></td></tr></table></td></tr></table><br /><br /></ContentTemplate></asp:UpdatePanel></asp:View></asp:MultiView><br /></ContentTemplate></asp:UpdatePanel></ContentTemplate></cc1:TabPanel>
                            </cc1:TabContainer>
                        </ContentTemplate>
                    </asp:UpdatePanel>
                
                            
                &nbsp;</td>
        </tr>
        <tr>
            <td>
                <br />
               
            </td>
        </tr>
    </table>
      </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>

